// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: authorization/authorization_message.proto

package authorizationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_authorization_authorization_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_message_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Request) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_authorization_authorization_message_proto protoreflect.FileDescriptor

const file_authorization_authorization_message_proto_rawDesc = "" +
	"\n" +
	")authorization/authorization_message.proto\x12\rauthorization\"K\n" +
	"\aRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ipBZZXgithub.com/zorg113/golang_dipl/atibruteforce/internal/controller/grpcapi/authorizationpbb\x06proto3"

var (
	file_authorization_authorization_message_proto_rawDescOnce sync.Once
	file_authorization_authorization_message_proto_rawDescData []byte
)

func file_authorization_authorization_message_proto_rawDescGZIP() []byte {
	file_authorization_authorization_message_proto_rawDescOnce.Do(func() {
		file_authorization_authorization_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_authorization_message_proto_rawDesc), len(file_authorization_authorization_message_proto_rawDesc)))
	})
	return file_authorization_authorization_message_proto_rawDescData
}

var file_authorization_authorization_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authorization_authorization_message_proto_goTypes = []any{
	(*Request)(nil), // 0: authorization.Request
}
var file_authorization_authorization_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authorization_authorization_message_proto_init() }
func file_authorization_authorization_message_proto_init() {
	if File_authorization_authorization_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_authorization_message_proto_rawDesc), len(file_authorization_authorization_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authorization_authorization_message_proto_goTypes,
		DependencyIndexes: file_authorization_authorization_message_proto_depIdxs,
		MessageInfos:      file_authorization_authorization_message_proto_msgTypes,
	}.Build()
	File_authorization_authorization_message_proto = out.File
	file_authorization_authorization_message_proto_goTypes = nil
	file_authorization_authorization_message_proto_depIdxs = nil
}
