
services:
  db:
    container_name: anti-bruteforce_database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/000001_create_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 10.0.0.2
  server:
    container_name: anti-bruteforce-services
    build: ./
    image: anti-bruteforce-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    # environment:
    #   DB_HOST: db
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_NAME: postgres
    #   SERVER_TYPE: grpc
    links:
      - db 
    volumes:
     - './:/src'
    networks:
      vpcbr:
        ipv4_address: 10.0.0.3
  server2:
    container_name: python-request
    image: python-request
    depends_on:
      - server        
    networks:
      vpcbr:
        ipv4_address: 10.0.0.4
    build:      
      dockerfile: ./pytest/Dockerfile
  

volumes:
  db:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1

