// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: whitelist/whitelist_service.proto

package whitelistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhiteList_AddIp_FullMethodName     = "/whitelist.WhiteList/AddIp"
	WhiteList_RemoveIp_FullMethodName  = "/whitelist.WhiteList/RemoveIp"
	WhiteList_GetIpList_FullMethodName = "/whitelist.WhiteList/GetIpList"
)

// WhiteListClient is the client API for WhiteList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhiteListClient interface {
	AddIp(ctx context.Context, in *AddIpRequest, opts ...grpc.CallOption) (*AddIpResponse, error)
	RemoveIp(ctx context.Context, in *RemoveIPRequest, opts ...grpc.CallOption) (*RemoveIPResponse, error)
	GetIpList(ctx context.Context, in *GetIpListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetIpListResponse], error)
}

type whiteListClient struct {
	cc grpc.ClientConnInterface
}

func NewWhiteListClient(cc grpc.ClientConnInterface) WhiteListClient {
	return &whiteListClient{cc}
}

func (c *whiteListClient) AddIp(ctx context.Context, in *AddIpRequest, opts ...grpc.CallOption) (*AddIpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddIpResponse)
	err := c.cc.Invoke(ctx, WhiteList_AddIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whiteListClient) RemoveIp(ctx context.Context, in *RemoveIPRequest, opts ...grpc.CallOption) (*RemoveIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveIPResponse)
	err := c.cc.Invoke(ctx, WhiteList_RemoveIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whiteListClient) GetIpList(ctx context.Context, in *GetIpListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetIpListResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WhiteList_ServiceDesc.Streams[0], WhiteList_GetIpList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetIpListRequest, GetIpListResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhiteList_GetIpListClient = grpc.ServerStreamingClient[GetIpListResponse]

// WhiteListServer is the server API for WhiteList service.
// All implementations must embed UnimplementedWhiteListServer
// for forward compatibility.
type WhiteListServer interface {
	AddIp(context.Context, *AddIpRequest) (*AddIpResponse, error)
	RemoveIp(context.Context, *RemoveIPRequest) (*RemoveIPResponse, error)
	GetIpList(*GetIpListRequest, grpc.ServerStreamingServer[GetIpListResponse]) error
	mustEmbedUnimplementedWhiteListServer()
}

// UnimplementedWhiteListServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhiteListServer struct{}

func (UnimplementedWhiteListServer) AddIp(context.Context, *AddIpRequest) (*AddIpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIp not implemented")
}
func (UnimplementedWhiteListServer) RemoveIp(context.Context, *RemoveIPRequest) (*RemoveIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIp not implemented")
}
func (UnimplementedWhiteListServer) GetIpList(*GetIpListRequest, grpc.ServerStreamingServer[GetIpListResponse]) error {
	return status.Error(codes.Unimplemented, "method GetIpList not implemented")
}
func (UnimplementedWhiteListServer) mustEmbedUnimplementedWhiteListServer() {}
func (UnimplementedWhiteListServer) testEmbeddedByValue()                   {}

// UnsafeWhiteListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhiteListServer will
// result in compilation errors.
type UnsafeWhiteListServer interface {
	mustEmbedUnimplementedWhiteListServer()
}

func RegisterWhiteListServer(s grpc.ServiceRegistrar, srv WhiteListServer) {
	// If the following call panics, it indicates UnimplementedWhiteListServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhiteList_ServiceDesc, srv)
}

func _WhiteList_AddIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhiteListServer).AddIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhiteList_AddIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhiteListServer).AddIp(ctx, req.(*AddIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhiteList_RemoveIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhiteListServer).RemoveIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhiteList_RemoveIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhiteListServer).RemoveIp(ctx, req.(*RemoveIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhiteList_GetIpList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetIpListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WhiteListServer).GetIpList(m, &grpc.GenericServerStream[GetIpListRequest, GetIpListResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhiteList_GetIpListServer = grpc.ServerStreamingServer[GetIpListResponse]

// WhiteList_ServiceDesc is the grpc.ServiceDesc for WhiteList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhiteList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitelist.WhiteList",
	HandlerType: (*WhiteListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddIp",
			Handler:    _WhiteList_AddIp_Handler,
		},
		{
			MethodName: "RemoveIp",
			Handler:    _WhiteList_RemoveIp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetIpList",
			Handler:       _WhiteList_GetIpList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "whitelist/whitelist_service.proto",
}
