// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: whitelist/whitelist_message.proto

package whitelistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask          string                 `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpNetwork) Reset() {
	*x = IpNetwork{}
	mi := &file_whitelist_whitelist_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpNetwork) ProtoMessage() {}

func (x *IpNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_whitelist_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpNetwork.ProtoReflect.Descriptor instead.
func (*IpNetwork) Descriptor() ([]byte, []int) {
	return file_whitelist_whitelist_message_proto_rawDescGZIP(), []int{0}
}

func (x *IpNetwork) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IpNetwork) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

var File_whitelist_whitelist_message_proto protoreflect.FileDescriptor

const file_whitelist_whitelist_message_proto_rawDesc = "" +
	"\n" +
	"!whitelist/whitelist_message.proto\x12\twhitelist\"/\n" +
	"\tIpNetwork\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04mask\x18\x02 \x01(\tR\x04maskBVZTgithub.com/zorg113/golang_dipl/atibruteforce/internal/controller/grpcapi/whitelistpbb\x06proto3"

var (
	file_whitelist_whitelist_message_proto_rawDescOnce sync.Once
	file_whitelist_whitelist_message_proto_rawDescData []byte
)

func file_whitelist_whitelist_message_proto_rawDescGZIP() []byte {
	file_whitelist_whitelist_message_proto_rawDescOnce.Do(func() {
		file_whitelist_whitelist_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitelist_whitelist_message_proto_rawDesc), len(file_whitelist_whitelist_message_proto_rawDesc)))
	})
	return file_whitelist_whitelist_message_proto_rawDescData
}

var file_whitelist_whitelist_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_whitelist_whitelist_message_proto_goTypes = []any{
	(*IpNetwork)(nil), // 0: whitelist.IpNetwork
}
var file_whitelist_whitelist_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_whitelist_whitelist_message_proto_init() }
func file_whitelist_whitelist_message_proto_init() {
	if File_whitelist_whitelist_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitelist_whitelist_message_proto_rawDesc), len(file_whitelist_whitelist_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whitelist_whitelist_message_proto_goTypes,
		DependencyIndexes: file_whitelist_whitelist_message_proto_depIdxs,
		MessageInfos:      file_whitelist_whitelist_message_proto_msgTypes,
	}.Build()
	File_whitelist_whitelist_message_proto = out.File
	file_whitelist_whitelist_message_proto_goTypes = nil
	file_whitelist_whitelist_message_proto_depIdxs = nil
}
