// Code generated by MockGen. DO NOT EDIT.
// Source: model/service/blacklist.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/zorg113/golang_dipl/atibruteforce/model/entity"
)

// MockBlackListStore is a mock of BlackListStore interface.
type MockBlackListStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlackListStoreMockRecorder
}

// MockBlackListStoreMockRecorder is the mock recorder for MockBlackListStore.
type MockBlackListStoreMockRecorder struct {
	mock *MockBlackListStore
}

// NewMockBlackListStore creates a new mock instance.
func NewMockBlackListStore(ctrl *gomock.Controller) *MockBlackListStore {
	mock := &MockBlackListStore{ctrl: ctrl}
	mock.recorder = &MockBlackListStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlackListStore) EXPECT() *MockBlackListStoreMockRecorder {
	return m.recorder
}

// AddIP mocks base method.
func (m *MockBlackListStore) AddIP(prefix, mask string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIP", prefix, mask)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIP indicates an expected call of AddIP.
func (mr *MockBlackListStoreMockRecorder) AddIP(prefix, mask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIP", reflect.TypeOf((*MockBlackListStore)(nil).AddIP), prefix, mask)
}

// DeleteIP mocks base method.
func (m *MockBlackListStore) DeleteIP(Prefix, mask string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIP", Prefix, mask)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIP indicates an expected call of DeleteIP.
func (mr *MockBlackListStoreMockRecorder) DeleteIP(Prefix, mask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIP", reflect.TypeOf((*MockBlackListStore)(nil).DeleteIP), Prefix, mask)
}

// GetIPs mocks base method.
func (m *MockBlackListStore) GetIPs() ([]entity.IpNetwork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPs")
	ret0, _ := ret[0].([]entity.IpNetwork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPs indicates an expected call of GetIPs.
func (mr *MockBlackListStoreMockRecorder) GetIPs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPs", reflect.TypeOf((*MockBlackListStore)(nil).GetIPs))
}
