// Code generated by MockGen. DO NOT EDIT.
// Source: model/service/whitelist.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/zorg113/golang_dipl/atibruteforce/model/entity"
)

// MockWhiteListStore is a mock of WhiteListStore interface.
type MockWhiteListStore struct {
	ctrl     *gomock.Controller
	recorder *MockWhiteListStoreMockRecorder
}

// MockWhiteListStoreMockRecorder is the mock recorder for MockWhiteListStore.
type MockWhiteListStoreMockRecorder struct {
	mock *MockWhiteListStore
}

// NewMockWhiteListStore creates a new mock instance.
func NewMockWhiteListStore(ctrl *gomock.Controller) *MockWhiteListStore {
	mock := &MockWhiteListStore{ctrl: ctrl}
	mock.recorder = &MockWhiteListStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhiteListStore) EXPECT() *MockWhiteListStoreMockRecorder {
	return m.recorder
}

// AddIP mocks base method.
func (m *MockWhiteListStore) AddIP(prefix, mask string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIP", prefix, mask)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIP indicates an expected call of AddIP.
func (mr *MockWhiteListStoreMockRecorder) AddIP(prefix, mask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIP", reflect.TypeOf((*MockWhiteListStore)(nil).AddIP), prefix, mask)
}

// DeleteIP mocks base method.
func (m *MockWhiteListStore) DeleteIP(prefix, mask string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIP", prefix, mask)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIP indicates an expected call of DeleteIP.
func (mr *MockWhiteListStoreMockRecorder) DeleteIP(prefix, mask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIP", reflect.TypeOf((*MockWhiteListStore)(nil).DeleteIP), prefix, mask)
}

// GetIPs mocks base method.
func (m *MockWhiteListStore) GetIPs() ([]entity.IpNetwork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPs")
	ret0, _ := ret[0].([]entity.IpNetwork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPs indicates an expected call of GetIPs.
func (mr *MockWhiteListStoreMockRecorder) GetIPs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPs", reflect.TypeOf((*MockWhiteListStore)(nil).GetIPs))
}
