listen:
    Type: port
    BindIP: 0.0.0.0
    Port: "8080"
server:
    ReadTimeout: 10
    WriteTimeout: 30
    IdleTimeout: 40
    ServerType: http
appconfig:
    LogLevel: info
dbdata:
    Host: 0.0.0.0
    DbName: postgres
    Port: "5432"
    DbUser: postgres
    DbPassword: postgres
    SslMode: "false"
bucket:
    IpLimit: 1000
    LoginLimit: 10
    PasswordLimit: 10
    ResetBucketInterval: 100
