listen:
    Type: port
    BindIP: 10.0.0.3
    Port: "8080"
server:
    ReadTimeout: 10
    WriteTimeout: 30
    IdleTimeout: 40
    ServerType: http
appconfig:
    LogLevel: info
dbdata:
    Host: 10.0.0.2
    DbName: postgres
    Port: "5432"
    DbUser: postgres
    DbPassword: postgres
    SslMode: "disable"
bucket:
    IpLimit: 1000
    LoginLimit: 10
    PasswordLimit: 10
    ResetBucketInterval: 100
