// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bucket/bucket_service.proto

package bucketpb

import (
	commonpb "github.com/zorg113/golang_dipl/atibruteforce/internal/controller/grpcapi/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *commonpb.Request      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBucketRequest) Reset() {
	*x = ResetBucketRequest{}
	mi := &file_bucket_bucket_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketRequest) ProtoMessage() {}

func (x *ResetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_bucket_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketRequest.ProtoReflect.Descriptor instead.
func (*ResetBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_bucket_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResetBucketRequest) GetRequest() *commonpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type ResetBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetLogin    bool                   `protobuf:"varint,1,opt,name=reset_login,json=resetLogin,proto3" json:"reset_login,omitempty"` // ← было resetLogin
	ResetIp       bool                   `protobuf:"varint,2,opt,name=reset_ip,json=resetIp,proto3" json:"reset_ip,omitempty"`          // ← было resetIp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBucketResponse) Reset() {
	*x = ResetBucketResponse{}
	mi := &file_bucket_bucket_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketResponse) ProtoMessage() {}

func (x *ResetBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_bucket_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketResponse.ProtoReflect.Descriptor instead.
func (*ResetBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_bucket_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResetBucketResponse) GetResetLogin() bool {
	if x != nil {
		return x.ResetLogin
	}
	return false
}

func (x *ResetBucketResponse) GetResetIp() bool {
	if x != nil {
		return x.ResetIp
	}
	return false
}

var File_bucket_bucket_service_proto protoreflect.FileDescriptor

const file_bucket_bucket_service_proto_rawDesc = "" +
	"\n" +
	"\x1bbucket/bucket_service.proto\x12\x06bucket\x1a\x13common/common.proto\"?\n" +
	"\x12ResetBucketRequest\x12)\n" +
	"\arequest\x18\x01 \x01(\v2\x0f.common.RequestR\arequest\"Q\n" +
	"\x13ResetBucketResponse\x12\x1f\n" +
	"\vreset_login\x18\x01 \x01(\bR\n" +
	"resetLogin\x12\x19\n" +
	"\breset_ip\x18\x02 \x01(\bR\aresetIp2P\n" +
	"\x06Bucket\x12F\n" +
	"\vResetBucket\x12\x1a.bucket.ResetBucketRequest\x1a\x1b.bucket.ResetBucketResponseBSZQgithub.com/zorg113/golang_dipl/atibruteforce/internal/controller/grpcapi/bucketpbb\x06proto3"

var (
	file_bucket_bucket_service_proto_rawDescOnce sync.Once
	file_bucket_bucket_service_proto_rawDescData []byte
)

func file_bucket_bucket_service_proto_rawDescGZIP() []byte {
	file_bucket_bucket_service_proto_rawDescOnce.Do(func() {
		file_bucket_bucket_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bucket_bucket_service_proto_rawDesc), len(file_bucket_bucket_service_proto_rawDesc)))
	})
	return file_bucket_bucket_service_proto_rawDescData
}

var file_bucket_bucket_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bucket_bucket_service_proto_goTypes = []any{
	(*ResetBucketRequest)(nil),  // 0: bucket.ResetBucketRequest
	(*ResetBucketResponse)(nil), // 1: bucket.ResetBucketResponse
	(*commonpb.Request)(nil),    // 2: common.Request
}
var file_bucket_bucket_service_proto_depIdxs = []int32{
	2, // 0: bucket.ResetBucketRequest.request:type_name -> common.Request
	0, // 1: bucket.Bucket.ResetBucket:input_type -> bucket.ResetBucketRequest
	1, // 2: bucket.Bucket.ResetBucket:output_type -> bucket.ResetBucketResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bucket_bucket_service_proto_init() }
func file_bucket_bucket_service_proto_init() {
	if File_bucket_bucket_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bucket_bucket_service_proto_rawDesc), len(file_bucket_bucket_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bucket_bucket_service_proto_goTypes,
		DependencyIndexes: file_bucket_bucket_service_proto_depIdxs,
		MessageInfos:      file_bucket_bucket_service_proto_msgTypes,
	}.Build()
	File_bucket_bucket_service_proto = out.File
	file_bucket_bucket_service_proto_goTypes = nil
	file_bucket_bucket_service_proto_depIdxs = nil
}
