name: CheckLintAndTest
on: push
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest                
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
        - name: Install golangci-lint
          run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        - name: Run golangci-lint
          run: golangci-lint run ./...

    test-diplom:
        runs-on: ubuntu-latest
        steps:
        - name: Set up on Go
          uses: actions/setup-go@v5
          with:
               go-version: 1.23
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3
        
        - name: build
          run: 
            make build
            
        - name: Test
          run: 
            make test
            