// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: blacklist/blacklist_service.proto

package blacklistpb

import (
	commonpb "github.com/zorg113/golang_dipl/atibruteforce/internal/controller/grpcapi/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddIpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNetwork     *commonpb.IpNetwork    `protobuf:"bytes,1,opt,name=ip_network,json=ipNetwork,proto3" json:"ip_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIpRequest) Reset() {
	*x = AddIpRequest{}
	mi := &file_blacklist_blacklist_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIpRequest) ProtoMessage() {}

func (x *AddIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_blacklist_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIpRequest.ProtoReflect.Descriptor instead.
func (*AddIpRequest) Descriptor() ([]byte, []int) {
	return file_blacklist_blacklist_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddIpRequest) GetIpNetwork() *commonpb.IpNetwork {
	if x != nil {
		return x.IpNetwork
	}
	return nil
}

type AddIpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAddIp       bool                   `protobuf:"varint,1,opt,name=is_add_ip,json=isAddIp,proto3" json:"is_add_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIpResponse) Reset() {
	*x = AddIpResponse{}
	mi := &file_blacklist_blacklist_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIpResponse) ProtoMessage() {}

func (x *AddIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_blacklist_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIpResponse.ProtoReflect.Descriptor instead.
func (*AddIpResponse) Descriptor() ([]byte, []int) {
	return file_blacklist_blacklist_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddIpResponse) GetIsAddIp() bool {
	if x != nil {
		return x.IsAddIp
	}
	return false
}

type RemoveIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNetwork     *commonpb.IpNetwork    `protobuf:"bytes,1,opt,name=ip_network,json=ipNetwork,proto3" json:"ip_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIPRequest) Reset() {
	*x = RemoveIPRequest{}
	mi := &file_blacklist_blacklist_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIPRequest) ProtoMessage() {}

func (x *RemoveIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_blacklist_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIPRequest.ProtoReflect.Descriptor instead.
func (*RemoveIPRequest) Descriptor() ([]byte, []int) {
	return file_blacklist_blacklist_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIPRequest) GetIpNetwork() *commonpb.IpNetwork {
	if x != nil {
		return x.IpNetwork
	}
	return nil
}

type RemoveIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRemoveIp    bool                   `protobuf:"varint,1,opt,name=is_remove_ip,json=isRemoveIp,proto3" json:"is_remove_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIPResponse) Reset() {
	*x = RemoveIPResponse{}
	mi := &file_blacklist_blacklist_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIPResponse) ProtoMessage() {}

func (x *RemoveIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_blacklist_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIPResponse.ProtoReflect.Descriptor instead.
func (*RemoveIPResponse) Descriptor() ([]byte, []int) {
	return file_blacklist_blacklist_service_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveIPResponse) GetIsRemoveIp() bool {
	if x != nil {
		return x.IsRemoveIp
	}
	return false
}

type GetIpListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     int32                  `protobuf:"varint,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpListRequest) Reset() {
	*x = GetIpListRequest{}
	mi := &file_blacklist_blacklist_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpListRequest) ProtoMessage() {}

func (x *GetIpListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_blacklist_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpListRequest.ProtoReflect.Descriptor instead.
func (*GetIpListRequest) Descriptor() ([]byte, []int) {
	return file_blacklist_blacklist_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetIpListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetIpListRequest) GetPageToken() int32 {
	if x != nil {
		return x.PageToken
	}
	return 0
}

type GetIpListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNetwork     *commonpb.IpNetwork    `protobuf:"bytes,1,opt,name=ip_network,json=ipNetwork,proto3" json:"ip_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpListResponse) Reset() {
	*x = GetIpListResponse{}
	mi := &file_blacklist_blacklist_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpListResponse) ProtoMessage() {}

func (x *GetIpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_blacklist_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpListResponse.ProtoReflect.Descriptor instead.
func (*GetIpListResponse) Descriptor() ([]byte, []int) {
	return file_blacklist_blacklist_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetIpListResponse) GetIpNetwork() *commonpb.IpNetwork {
	if x != nil {
		return x.IpNetwork
	}
	return nil
}

var File_blacklist_blacklist_service_proto protoreflect.FileDescriptor

const file_blacklist_blacklist_service_proto_rawDesc = "" +
	"\n" +
	"!blacklist/blacklist_service.proto\x12\tblacklist\x1a\x13common/common.proto\"@\n" +
	"\fAddIpRequest\x120\n" +
	"\n" +
	"ip_network\x18\x01 \x01(\v2\x11.common.IpNetworkR\tipNetwork\"+\n" +
	"\rAddIpResponse\x12\x1a\n" +
	"\tis_add_ip\x18\x01 \x01(\bR\aisAddIp\"C\n" +
	"\x0fRemoveIPRequest\x120\n" +
	"\n" +
	"ip_network\x18\x01 \x01(\v2\x11.common.IpNetworkR\tipNetwork\"4\n" +
	"\x10RemoveIPResponse\x12 \n" +
	"\fis_remove_ip\x18\x01 \x01(\bR\n" +
	"isRemoveIp\"N\n" +
	"\x10GetIpListRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\x05R\tpageToken\"E\n" +
	"\x11GetIpListResponse\x120\n" +
	"\n" +
	"ip_network\x18\x01 \x01(\v2\x11.common.IpNetworkR\tipNetwork2\xd6\x01\n" +
	"\tBlackList\x12:\n" +
	"\x05AddIp\x12\x17.blacklist.AddIpRequest\x1a\x18.blacklist.AddIpResponse\x12C\n" +
	"\bRemoveIp\x12\x1a.blacklist.RemoveIPRequest\x1a\x1b.blacklist.RemoveIPResponse\x12H\n" +
	"\tGetIpList\x12\x1b.blacklist.GetIpListRequest\x1a\x1c.blacklist.GetIpListResponse0\x01BVZTgithub.com/zorg113/golang_dipl/atibruteforce/internal/controller/grpcapi/blacklistpbb\x06proto3"

var (
	file_blacklist_blacklist_service_proto_rawDescOnce sync.Once
	file_blacklist_blacklist_service_proto_rawDescData []byte
)

func file_blacklist_blacklist_service_proto_rawDescGZIP() []byte {
	file_blacklist_blacklist_service_proto_rawDescOnce.Do(func() {
		file_blacklist_blacklist_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blacklist_blacklist_service_proto_rawDesc), len(file_blacklist_blacklist_service_proto_rawDesc)))
	})
	return file_blacklist_blacklist_service_proto_rawDescData
}

var file_blacklist_blacklist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_blacklist_blacklist_service_proto_goTypes = []any{
	(*AddIpRequest)(nil),       // 0: blacklist.AddIpRequest
	(*AddIpResponse)(nil),      // 1: blacklist.AddIpResponse
	(*RemoveIPRequest)(nil),    // 2: blacklist.RemoveIPRequest
	(*RemoveIPResponse)(nil),   // 3: blacklist.RemoveIPResponse
	(*GetIpListRequest)(nil),   // 4: blacklist.GetIpListRequest
	(*GetIpListResponse)(nil),  // 5: blacklist.GetIpListResponse
	(*commonpb.IpNetwork)(nil), // 6: common.IpNetwork
}
var file_blacklist_blacklist_service_proto_depIdxs = []int32{
	6, // 0: blacklist.AddIpRequest.ip_network:type_name -> common.IpNetwork
	6, // 1: blacklist.RemoveIPRequest.ip_network:type_name -> common.IpNetwork
	6, // 2: blacklist.GetIpListResponse.ip_network:type_name -> common.IpNetwork
	0, // 3: blacklist.BlackList.AddIp:input_type -> blacklist.AddIpRequest
	2, // 4: blacklist.BlackList.RemoveIp:input_type -> blacklist.RemoveIPRequest
	4, // 5: blacklist.BlackList.GetIpList:input_type -> blacklist.GetIpListRequest
	1, // 6: blacklist.BlackList.AddIp:output_type -> blacklist.AddIpResponse
	3, // 7: blacklist.BlackList.RemoveIp:output_type -> blacklist.RemoveIPResponse
	5, // 8: blacklist.BlackList.GetIpList:output_type -> blacklist.GetIpListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blacklist_blacklist_service_proto_init() }
func file_blacklist_blacklist_service_proto_init() {
	if File_blacklist_blacklist_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blacklist_blacklist_service_proto_rawDesc), len(file_blacklist_blacklist_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blacklist_blacklist_service_proto_goTypes,
		DependencyIndexes: file_blacklist_blacklist_service_proto_depIdxs,
		MessageInfos:      file_blacklist_blacklist_service_proto_msgTypes,
	}.Build()
	File_blacklist_blacklist_service_proto = out.File
	file_blacklist_blacklist_service_proto_goTypes = nil
	file_blacklist_blacklist_service_proto_depIdxs = nil
}
