// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: blacklist/blacklist_service.proto

package blacklistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlackList_AddIp_FullMethodName     = "/blacklist.BlackList/AddIp"
	BlackList_RemoveIp_FullMethodName  = "/blacklist.BlackList/RemoveIp"
	BlackList_GetIpList_FullMethodName = "/blacklist.BlackList/GetIpList"
)

// BlackListClient is the client API for BlackList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlackListClient interface {
	AddIp(ctx context.Context, in *AddIpRequest, opts ...grpc.CallOption) (*AddIpResponse, error)
	RemoveIp(ctx context.Context, in *RemoveIPRequest, opts ...grpc.CallOption) (*RemoveIPResponse, error)
	GetIpList(ctx context.Context, in *GetIpListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetIpListResponse], error)
}

type blackListClient struct {
	cc grpc.ClientConnInterface
}

func NewBlackListClient(cc grpc.ClientConnInterface) BlackListClient {
	return &blackListClient{cc}
}

func (c *blackListClient) AddIp(ctx context.Context, in *AddIpRequest, opts ...grpc.CallOption) (*AddIpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddIpResponse)
	err := c.cc.Invoke(ctx, BlackList_AddIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blackListClient) RemoveIp(ctx context.Context, in *RemoveIPRequest, opts ...grpc.CallOption) (*RemoveIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveIPResponse)
	err := c.cc.Invoke(ctx, BlackList_RemoveIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blackListClient) GetIpList(ctx context.Context, in *GetIpListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetIpListResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlackList_ServiceDesc.Streams[0], BlackList_GetIpList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetIpListRequest, GetIpListResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlackList_GetIpListClient = grpc.ServerStreamingClient[GetIpListResponse]

// BlackListServer is the server API for BlackList service.
// All implementations must embed UnimplementedBlackListServer
// for forward compatibility.
type BlackListServer interface {
	AddIp(context.Context, *AddIpRequest) (*AddIpResponse, error)
	RemoveIp(context.Context, *RemoveIPRequest) (*RemoveIPResponse, error)
	GetIpList(*GetIpListRequest, grpc.ServerStreamingServer[GetIpListResponse]) error
	mustEmbedUnimplementedBlackListServer()
}

// UnimplementedBlackListServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlackListServer struct{}

func (UnimplementedBlackListServer) AddIp(context.Context, *AddIpRequest) (*AddIpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIp not implemented")
}
func (UnimplementedBlackListServer) RemoveIp(context.Context, *RemoveIPRequest) (*RemoveIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIp not implemented")
}
func (UnimplementedBlackListServer) GetIpList(*GetIpListRequest, grpc.ServerStreamingServer[GetIpListResponse]) error {
	return status.Error(codes.Unimplemented, "method GetIpList not implemented")
}
func (UnimplementedBlackListServer) mustEmbedUnimplementedBlackListServer() {}
func (UnimplementedBlackListServer) testEmbeddedByValue()                   {}

// UnsafeBlackListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlackListServer will
// result in compilation errors.
type UnsafeBlackListServer interface {
	mustEmbedUnimplementedBlackListServer()
}

func RegisterBlackListServer(s grpc.ServiceRegistrar, srv BlackListServer) {
	// If the following call panics, it indicates UnimplementedBlackListServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlackList_ServiceDesc, srv)
}

func _BlackList_AddIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackListServer).AddIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlackList_AddIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackListServer).AddIp(ctx, req.(*AddIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlackList_RemoveIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackListServer).RemoveIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlackList_RemoveIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackListServer).RemoveIp(ctx, req.(*RemoveIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlackList_GetIpList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetIpListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlackListServer).GetIpList(m, &grpc.GenericServerStream[GetIpListRequest, GetIpListResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlackList_GetIpListServer = grpc.ServerStreamingServer[GetIpListResponse]

// BlackList_ServiceDesc is the grpc.ServiceDesc for BlackList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlackList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blacklist.BlackList",
	HandlerType: (*BlackListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddIp",
			Handler:    _BlackList_AddIp_Handler,
		},
		{
			MethodName: "RemoveIp",
			Handler:    _BlackList_RemoveIp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetIpList",
			Handler:       _BlackList_GetIpList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blacklist/blacklist_service.proto",
}
